//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNumismat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eNumismat.de", typeof(de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adressbuch.
        /// </summary>
        internal static string _addrBook {
            get {
                return ResourceManager.GetString("_addrBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank sichern.
        /// </summary>
        internal static string _backupDataBase {
            get {
                return ResourceManager.GetString("_backupDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache ändern.
        /// </summary>
        internal static string _changeLanguage {
            get {
                return ResourceManager.GetString("_changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank komprimieren.
        /// </summary>
        internal static string _compressDataBase {
            get {
                return ResourceManager.GetString("_compressDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Datenbank.
        /// </summary>
        internal static string _createNewDataBase {
            get {
                return ResourceManager.GetString("_createNewDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen bearbeiten.
        /// </summary>
        internal static string _editSettings {
            get {
                return ResourceManager.GetString("_editSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string _exitApplication {
            get {
                return ResourceManager.GetString("_exitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string _extras {
            get {
                return ResourceManager.GetString("_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string _file {
            get {
                return ResourceManager.GetString("_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch.
        /// </summary>
        internal static string _langEnglish {
            get {
                return ResourceManager.GetString("_langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französisch.
        /// </summary>
        internal static string _langFrench {
            get {
                return ResourceManager.GetString("_langFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string _langGerman {
            get {
                return ResourceManager.GetString("_langGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Kontakt.
        /// </summary>
        internal static string _newContact {
            get {
                return ResourceManager.GetString("_newContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank öffnen.
        /// </summary>
        internal static string _openExistingDataBase {
            get {
                return ResourceManager.GetString("_openExistingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string _settings {
            get {
                return ResourceManager.GetString("_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tauschmonitor.
        /// </summary>
        internal static string _swapMonitor {
            get {
                return ResourceManager.GetString("_swapMonitor", resourceCulture);
            }
        }
    }
}
