//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNumismat {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class deu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal deu() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eNumismat.deu", typeof(deu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geburtstag: ähnelt.
        /// </summary>
        internal static string _addr_birthdate {
            get {
                return ResourceManager.GetString("_addr_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeigt ein leeres Forumlar an, um einen neuen Kontakt anzulegen ähnelt.
        /// </summary>
        internal static string _addr_btnCreate {
            get {
                return ResourceManager.GetString("_addr_btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löscht den aktuell ausgewählten Kontakt ähnelt.
        /// </summary>
        internal static string _addr_btnDelete {
            get {
                return ResourceManager.GetString("_addr_btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeigt ein Formular, welches mit den Daten des ausgewählten Kontakts befüllt ist, um diesen zu bearbeiten ähnelt.
        /// </summary>
        internal static string _addr_btnEdit {
            get {
                return ResourceManager.GetString("_addr_btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ort: ähnelt.
        /// </summary>
        internal static string _addr_city {
            get {
                return ResourceManager.GetString("_addr_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Land: ähnelt.
        /// </summary>
        internal static string _addr_country {
            get {
                return ResourceManager.GetString("_addr_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschlecht ähnelt.
        /// </summary>
        internal static string _addr_gender {
            get {
                return ResourceManager.GetString("_addr_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nr.: ähnelt.
        /// </summary>
        internal static string _addr_hnumber {
            get {
                return ResourceManager.GetString("_addr_hnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail: ähnelt.
        /// </summary>
        internal static string _addr_mail {
            get {
                return ResourceManager.GetString("_addr_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mobil: ähnelt.
        /// </summary>
        internal static string _addr_mobile {
            get {
                return ResourceManager.GetString("_addr_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string _addr_Name {
            get {
                return ResourceManager.GetString("_addr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notizen: ähnelt.
        /// </summary>
        internal static string _addr_notes {
            get {
                return ResourceManager.GetString("_addr_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon: ähnelt.
        /// </summary>
        internal static string _addr_phone {
            get {
                return ResourceManager.GetString("_addr_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße ähnelt.
        /// </summary>
        internal static string _addr_street {
            get {
                return ResourceManager.GetString("_addr_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorname: ähnelt.
        /// </summary>
        internal static string _addr_SureName {
            get {
                return ResourceManager.GetString("_addr_SureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontaktdaten ähnelt.
        /// </summary>
        internal static string _addr_tab_contactDetails {
            get {
                return ResourceManager.GetString("_addr_tab_contactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tauschübersicht ähnelt.
        /// </summary>
        internal static string _addr_tab_swaps {
            get {
                return ResourceManager.GetString("_addr_tab_swaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLZ: ähnelt.
        /// </summary>
        internal static string _addr_zipCode {
            get {
                return ResourceManager.GetString("_addr_zipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adressbuch ähnelt.
        /// </summary>
        internal static string _addrBook {
            get {
                return ResourceManager.GetString("_addrBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Name&quot; darf nicht leer sein! ähnelt.
        /// </summary>
        internal static string _addrBook_Validation_Name {
            get {
                return ResourceManager.GetString("_addrBook_Validation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld &quot;Vorname&quot; darf nicht leer sein! ähnelt.
        /// </summary>
        internal static string _addrBook_Validation_SureName {
            get {
                return ResourceManager.GetString("_addrBook_Validation_SureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank sichern ähnelt.
        /// </summary>
        internal static string _backupDataBase {
            get {
                return ResourceManager.GetString("_backupDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ändern ähnelt.
        /// </summary>
        internal static string _changeLanguage {
            get {
                return ResourceManager.GetString("_changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank komprimieren ähnelt.
        /// </summary>
        internal static string _compressDataBase {
            get {
                return ResourceManager.GetString("_compressDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontakt vorhanden ähnelt.
        /// </summary>
        internal static string _contactAvailable {
            get {
                return ResourceManager.GetString("_contactAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontakte vorhanden ähnelt.
        /// </summary>
        internal static string _contactsAvailable {
            get {
                return ResourceManager.GetString("_contactsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Datenbank ähnelt.
        /// </summary>
        internal static string _createNewDataBase {
            get {
                return ResourceManager.GetString("_createNewDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen bearbeiten ähnelt.
        /// </summary>
        internal static string _editSettings {
            get {
                return ResourceManager.GetString("_editSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        internal static string _exitApplication {
            get {
                return ResourceManager.GetString("_exitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extras ähnelt.
        /// </summary>
        internal static string _extras {
            get {
                return ResourceManager.GetString("_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        internal static string _file {
            get {
                return ResourceManager.GetString("_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        /// </summary>
        internal static string _langEnglish {
            get {
                return ResourceManager.GetString("_langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Französisch ähnelt.
        /// </summary>
        internal static string _langFrench {
            get {
                return ResourceManager.GetString("_langFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string _langGerman {
            get {
                return ResourceManager.GetString("_langGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Kontakt ähnelt.
        /// </summary>
        internal static string _newContact {
            get {
                return ResourceManager.GetString("_newContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Datenbank verbunden ähnelt.
        /// </summary>
        internal static string _noDBconnected {
            get {
                return ResourceManager.GetString("_noDBconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank öffnen ähnelt.
        /// </summary>
        internal static string _openExistingDataBase {
            get {
                return ResourceManager.GetString("_openExistingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string _settings {
            get {
                return ResourceManager.GetString("_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eingehend: ähnelt.
        /// </summary>
        internal static string _swap_incomming {
            get {
                return ResourceManager.GetString("_swap_incomming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgehend: ähnelt.
        /// </summary>
        internal static string _swap_outgoing {
            get {
                return ResourceManager.GetString("_swap_outgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tauschmonitor ähnelt.
        /// </summary>
        internal static string _swapMonitor {
            get {
                return ResourceManager.GetString("_swapMonitor", resourceCulture);
            }
        }
    }
}
