//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNumismat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eNumismat.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string _addr_birthdate {
            get {
                return ResourceManager.GetString("_addr_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string _addr_city {
            get {
                return ResourceManager.GetString("_addr_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string _addr_country {
            get {
                return ResourceManager.GetString("_addr_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string _addr_gender {
            get {
                return ResourceManager.GetString("_addr_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string _addr_hnumber {
            get {
                return ResourceManager.GetString("_addr_hnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eMail.
        /// </summary>
        internal static string _addr_mail {
            get {
                return ResourceManager.GetString("_addr_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string _addr_mobile {
            get {
                return ResourceManager.GetString("_addr_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string _addr_Name {
            get {
                return ResourceManager.GetString("_addr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _addr_notes {
            get {
                return ResourceManager.GetString("_addr_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string _addr_phone {
            get {
                return ResourceManager.GetString("_addr_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string _addr_street {
            get {
                return ResourceManager.GetString("_addr_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surename.
        /// </summary>
        internal static string _addr_SureName {
            get {
                return ResourceManager.GetString("_addr_SureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string _addr_zipCode {
            get {
                return ResourceManager.GetString("_addr_zipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressbook.
        /// </summary>
        internal static string _addrBook {
            get {
                return ResourceManager.GetString("_addrBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        internal static string _backupDataBase {
            get {
                return ResourceManager.GetString("_backupDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string _changeLanguage {
            get {
                return ResourceManager.GetString("_changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress Database.
        /// </summary>
        internal static string _compressDataBase {
            get {
                return ResourceManager.GetString("_compressDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database.
        /// </summary>
        internal static string _createNewDataBase {
            get {
                return ResourceManager.GetString("_createNewDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Settings.
        /// </summary>
        internal static string _editSettings {
            get {
                return ResourceManager.GetString("_editSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string _exitApplication {
            get {
                return ResourceManager.GetString("_exitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string _extras {
            get {
                return ResourceManager.GetString("_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string _file {
            get {
                return ResourceManager.GetString("_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string _langEnglish {
            get {
                return ResourceManager.GetString("_langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string _langFrench {
            get {
                return ResourceManager.GetString("_langFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string _langGerman {
            get {
                return ResourceManager.GetString("_langGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        internal static string _newContact {
            get {
                return ResourceManager.GetString("_newContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Database.
        /// </summary>
        internal static string _openExistingDataBase {
            get {
                return ResourceManager.GetString("_openExistingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string _settings {
            get {
                return ResourceManager.GetString("_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Monitor.
        /// </summary>
        internal static string _swapMonitor {
            get {
                return ResourceManager.GetString("_swapMonitor", resourceCulture);
            }
        }
    }
}
