//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNumismat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eNumismat.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversaire.
        /// </summary>
        internal static string _addr_birthdate {
            get {
                return ResourceManager.GetString("_addr_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        internal static string _addr_city {
            get {
                return ResourceManager.GetString("_addr_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        internal static string _addr_country {
            get {
                return ResourceManager.GetString("_addr_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexe.
        /// </summary>
        internal static string _addr_gender {
            get {
                return ResourceManager.GetString("_addr_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de la maison.
        /// </summary>
        internal static string _addr_hnumber {
            get {
                return ResourceManager.GetString("_addr_hnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string _addr_mail {
            get {
                return ResourceManager.GetString("_addr_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string _addr_mobile {
            get {
                return ResourceManager.GetString("_addr_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de famille.
        /// </summary>
        internal static string _addr_Name {
            get {
                return ResourceManager.GetString("_addr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _addr_notes {
            get {
                return ResourceManager.GetString("_addr_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        internal static string _addr_phone {
            get {
                return ResourceManager.GetString("_addr_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue.
        /// </summary>
        internal static string _addr_street {
            get {
                return ResourceManager.GetString("_addr_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string _addr_SureName {
            get {
                return ResourceManager.GetString("_addr_SureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de contact.
        /// </summary>
        internal static string _addr_tab_contactDetails {
            get {
                return ResourceManager.GetString("_addr_tab_contactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste d&apos;échange.
        /// </summary>
        internal static string _addr_tab_swaps {
            get {
                return ResourceManager.GetString("_addr_tab_swaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal.
        /// </summary>
        internal static string _addr_zipCode {
            get {
                return ResourceManager.GetString("_addr_zipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnet d&apos;adresses.
        /// </summary>
        internal static string _addrBook {
            get {
                return ResourceManager.GetString("_addrBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer la base de données.
        /// </summary>
        internal static string _backupDataBase {
            get {
                return ResourceManager.GetString("_backupDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer de langue.
        /// </summary>
        internal static string _changeLanguage {
            get {
                return ResourceManager.GetString("_changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de données compacte.
        /// </summary>
        internal static string _compressDataBase {
            get {
                return ResourceManager.GetString("_compressDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle base de données.
        /// </summary>
        internal static string _createNewDataBase {
            get {
                return ResourceManager.GetString("_createNewDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier les paramètres.
        /// </summary>
        internal static string _editSettings {
            get {
                return ResourceManager.GetString("_editSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laisser.
        /// </summary>
        internal static string _exitApplication {
            get {
                return ResourceManager.GetString("_exitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string _extras {
            get {
                return ResourceManager.GetString("_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        internal static string _file {
            get {
                return ResourceManager.GetString("_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        internal static string _langEnglish {
            get {
                return ResourceManager.GetString("_langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string _langFrench {
            get {
                return ResourceManager.GetString("_langFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allemand.
        /// </summary>
        internal static string _langGerman {
            get {
                return ResourceManager.GetString("_langGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau contact.
        /// </summary>
        internal static string _newContact {
            get {
                return ResourceManager.GetString("_newContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de données ouverte.
        /// </summary>
        internal static string _openExistingDataBase {
            get {
                return ResourceManager.GetString("_openExistingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string _settings {
            get {
                return ResourceManager.GetString("_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échange moniteur.
        /// </summary>
        internal static string _swapMonitor {
            get {
                return ResourceManager.GetString("_swapMonitor", resourceCulture);
            }
        }
    }
}
