//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNumismat {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fra {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fra() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eNumismat.fra", typeof(fra).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anniversaire: ähnelt.
        /// </summary>
        internal static string _addr_birthdate {
            get {
                return ResourceManager.GetString("_addr_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Affiche un forum vide pour créer un nouveau contact ähnelt.
        /// </summary>
        internal static string _addr_btnCreate {
            get {
                return ResourceManager.GetString("_addr_btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supprime le contact actuellement sélectionné ähnelt.
        /// </summary>
        internal static string _addr_btnDelete {
            get {
                return ResourceManager.GetString("_addr_btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Affiche un formulaire rempli avec les données du contact sélectionné pour le modifier ähnelt.
        /// </summary>
        internal static string _addr_btnEdit {
            get {
                return ResourceManager.GetString("_addr_btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ville: ähnelt.
        /// </summary>
        internal static string _addr_city {
            get {
                return ResourceManager.GetString("_addr_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pays: ähnelt.
        /// </summary>
        internal static string _addr_country {
            get {
                return ResourceManager.GetString("_addr_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sexe: ähnelt.
        /// </summary>
        internal static string _addr_gender {
            get {
                return ResourceManager.GetString("_addr_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numéro: ähnelt.
        /// </summary>
        internal static string _addr_hnumber {
            get {
                return ResourceManager.GetString("_addr_hnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail: ähnelt.
        /// </summary>
        internal static string _addr_mail {
            get {
                return ResourceManager.GetString("_addr_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mobile: ähnelt.
        /// </summary>
        internal static string _addr_mobile {
            get {
                return ResourceManager.GetString("_addr_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nom de famille: ähnelt.
        /// </summary>
        internal static string _addr_Name {
            get {
                return ResourceManager.GetString("_addr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes: ähnelt.
        /// </summary>
        internal static string _addr_notes {
            get {
                return ResourceManager.GetString("_addr_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Téléphone: ähnelt.
        /// </summary>
        internal static string _addr_phone {
            get {
                return ResourceManager.GetString("_addr_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rue ähnelt.
        /// </summary>
        internal static string _addr_street {
            get {
                return ResourceManager.GetString("_addr_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prénom: ähnelt.
        /// </summary>
        internal static string _addr_SureName {
            get {
                return ResourceManager.GetString("_addr_SureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Détails de contact ähnelt.
        /// </summary>
        internal static string _addr_tab_contactDetails {
            get {
                return ResourceManager.GetString("_addr_tab_contactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liste d&apos;échange ähnelt.
        /// </summary>
        internal static string _addr_tab_swaps {
            get {
                return ResourceManager.GetString("_addr_tab_swaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code postal: ähnelt.
        /// </summary>
        internal static string _addr_zipCode {
            get {
                return ResourceManager.GetString("_addr_zipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carnet d&apos;adresses ähnelt.
        /// </summary>
        internal static string _addrBook {
            get {
                return ResourceManager.GetString("_addrBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le champ &quot;Nom&quot; ne peut pas être vide! ähnelt.
        /// </summary>
        internal static string _addrBook_Validation_Name {
            get {
                return ResourceManager.GetString("_addrBook_Validation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le champ &quot;prénom&quot; ne doit pas être vide! ähnelt.
        /// </summary>
        internal static string _addrBook_Validation_SureName {
            get {
                return ResourceManager.GetString("_addrBook_Validation_SureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enregistrer la base de données ähnelt.
        /// </summary>
        internal static string _backupDataBase {
            get {
                return ResourceManager.GetString("_backupDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changer de langue ähnelt.
        /// </summary>
        internal static string _changeLanguage {
            get {
                return ResourceManager.GetString("_changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base de données compacte ähnelt.
        /// </summary>
        internal static string _compressDataBase {
            get {
                return ResourceManager.GetString("_compressDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact disponible ähnelt.
        /// </summary>
        internal static string _contactAvailable {
            get {
                return ResourceManager.GetString("_contactAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contacts disponibles ähnelt.
        /// </summary>
        internal static string _contactsAvailable {
            get {
                return ResourceManager.GetString("_contactsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nouvelle base de données ähnelt.
        /// </summary>
        internal static string _createNewDataBase {
            get {
                return ResourceManager.GetString("_createNewDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modifier les paramètres ähnelt.
        /// </summary>
        internal static string _editSettings {
            get {
                return ResourceManager.GetString("_editSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laisser ähnelt.
        /// </summary>
        internal static string _exitApplication {
            get {
                return ResourceManager.GetString("_exitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extras ähnelt.
        /// </summary>
        internal static string _extras {
            get {
                return ResourceManager.GetString("_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fichier ähnelt.
        /// </summary>
        internal static string _file {
            get {
                return ResourceManager.GetString("_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anglais ähnelt.
        /// </summary>
        internal static string _langEnglish {
            get {
                return ResourceManager.GetString("_langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Français ähnelt.
        /// </summary>
        internal static string _langFrench {
            get {
                return ResourceManager.GetString("_langFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allemand ähnelt.
        /// </summary>
        internal static string _langGerman {
            get {
                return ResourceManager.GetString("_langGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nouveau contact ähnelt.
        /// </summary>
        internal static string _newContact {
            get {
                return ResourceManager.GetString("_newContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pas de base de données connectée ähnelt.
        /// </summary>
        internal static string _noDBconnected {
            get {
                return ResourceManager.GetString("_noDBconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base de données ouverte ähnelt.
        /// </summary>
        internal static string _openExistingDataBase {
            get {
                return ResourceManager.GetString("_openExistingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paramètres ähnelt.
        /// </summary>
        internal static string _settings {
            get {
                return ResourceManager.GetString("_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entrants: ähnelt.
        /// </summary>
        internal static string _swap_incomming {
            get {
                return ResourceManager.GetString("_swap_incomming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sortant: ähnelt.
        /// </summary>
        internal static string _swap_outgoing {
            get {
                return ResourceManager.GetString("_swap_outgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Échange moniteur ähnelt.
        /// </summary>
        internal static string _swapMonitor {
            get {
                return ResourceManager.GetString("_swapMonitor", resourceCulture);
            }
        }
    }
}
